### ISSUE TITLE
Support Typescript Rug archives

### ISSUE THREAD

**Issue by Lawouach** [atomist-rugs/rug-archive#6]
In addition to creating a DSL-based Rug, it would be nice to be able to generate TypeScript based archives.

**Comment by Lawouach** [comment]
Discussing with @russmiles, we should probably not populate the archive with an initial DSL Rug but add two editors to add a basic Rug DSL or a Rug typescript to an archive.

A Rug archive is the .atomist directory and the manifest.

**Comment by ddgenome** [comment]
Handled by atomist-rugs/rug-project.
